<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\RolePermission;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    /**
     * @var array<string, array<string, array<string, bool>>>
     */
    private const TEMPLATE = [
        'platform' => [
            'super_admin' => [
                'platform.dashboard.view' => true,
                'platform.businesses.view' => true,
                'platform.businesses.manage' => true,
                'platform.businesses.impersonate' => true,
                'platform.onboarding.manage' => true,
                'platform.plans.view' => true,
                'platform.plans.manage' => true,
                'platform.billing_truth.view' => true,
                'platform.billing_truth.manage' => true,
                'platform.usage_controls.view' => true,
                'platform.usage_controls.manage' => true,
                'platform.llm_keys.view_metadata' => true,
                'platform.llm_keys.manage' => true,
                'platform.voice_admin.view' => true,
                'platform.voice_admin.manage' => true,
                'platform.monitoring.view' => true,
                'platform.compliance.view' => true,
                'platform.compliance.approve' => true,
                'platform.compliance.execute' => true,
                'platform.retention.manage' => true,
                'platform.support.actions' => true,
                'platform.audit.view' => true,
                'platform.credentials.view_metadata' => true,
                'platform.credentials.manage' => true,
                'platform.ai_guardrails.manage' => true,
                'platform.horizon.view' => true,
            ],
            'support_admin' => [
                'platform.dashboard.view' => true,
                'platform.businesses.view' => true,
                'platform.businesses.manage' => false,
                'platform.businesses.impersonate' => true,
                'platform.onboarding.manage' => true,
                'platform.plans.view' => true,
                'platform.plans.manage' => false,
                'platform.billing_truth.view' => true,
                'platform.billing_truth.manage' => false,
                'platform.usage_controls.view' => true,
                'platform.usage_controls.manage' => false,
                'platform.llm_keys.view_metadata' => true,
                'platform.llm_keys.manage' => false,
                'platform.voice_admin.view' => true,
                'platform.voice_admin.manage' => false,
                'platform.monitoring.view' => true,
                'platform.compliance.view' => true,
                'platform.compliance.approve' => false,
                'platform.compliance.execute' => false,
                'platform.retention.manage' => false,
                'platform.support.actions' => true,
                'platform.audit.view' => true,
                'platform.credentials.view_metadata' => true,
                'platform.credentials.manage' => false,
                'platform.ai_guardrails.manage' => false,
                'platform.horizon.view' => true,
            ],
        ],
        'business' => [
            'business_owner' => [
                'business.dashboard.view' => true,
                'business.conversations.view' => true,
                'business.conversations.manage' => true,
                'business.conversations.takeover' => true,
                'business.appointments.view' => true,
                'business.appointments.manage' => true,
                'business.providers.view' => true,
                'business.providers.manage' => true,
                'business.patients.view' => true,
                'business.patients.manage' => true,
                'business.services.view' => true,
                'business.services.manage' => true,
                'business.ai_content.view' => true,
                'business.ai_content.manage' => true,
                'business.reminders.view' => true,
                'business.reminders.manage' => true,
                'business.integrations.view' => true,
                'business.integrations.manage' => true,
                'business.channels.view' => true,
                'business.channels.approve' => true,
                'business.voice_preferences.view' => true,
                'business.voice_preferences.manage' => true,
                'business.diagnostics.view' => true,
                'business.diagnostics.run' => true,
                'business.usage.view' => true,
                'business.billing.view' => true,
                'business.billing.portal' => true,
                'business.team.view' => true,
                'business.team.manage' => true,
                'business.roles.manage' => true,
                'business.security.view' => true,
                'business.security.manage' => true,
                'business.data_export.request' => true,
                'business.data_controls.view' => true,
                'business.data_delete.request' => true,
            ],
            'manager' => [
                'business.dashboard.view' => true,
                'business.conversations.view' => true,
                'business.conversations.manage' => true,
                'business.conversations.takeover' => true,
                'business.appointments.view' => true,
                'business.appointments.manage' => true,
                'business.providers.view' => true,
                'business.providers.manage' => true,
                'business.patients.view' => true,
                'business.patients.manage' => true,
                'business.services.view' => true,
                'business.services.manage' => true,
                'business.ai_content.view' => true,
                'business.ai_content.manage' => true,
                'business.reminders.view' => true,
                'business.reminders.manage' => true,
                'business.integrations.view' => true,
                'business.integrations.manage' => false,
                'business.channels.view' => true,
                'business.channels.approve' => false,
                'business.voice_preferences.view' => true,
                'business.voice_preferences.manage' => true,
                'business.diagnostics.view' => true,
                'business.diagnostics.run' => true,
                'business.usage.view' => true,
                'business.billing.view' => false,
                'business.billing.portal' => false,
                'business.team.view' => true,
                'business.team.manage' => false,
                'business.roles.manage' => false,
                'business.security.view' => true,
                'business.security.manage' => false,
                'business.data_export.request' => false,
                'business.data_controls.view' => true,
                'business.data_delete.request' => false,
            ],
            'receptionist' => [
                'business.dashboard.view' => true,
                'business.conversations.view' => true,
                'business.conversations.manage' => true,
                'business.conversations.takeover' => true,
                'business.appointments.view' => true,
                'business.appointments.manage' => true,
                'business.providers.view' => true,
                'business.providers.manage' => false,
                'business.patients.view' => true,
                'business.patients.manage' => true,
                'business.services.view' => true,
                'business.services.manage' => false,
                'business.ai_content.view' => false,
                'business.ai_content.manage' => false,
                'business.reminders.view' => false,
                'business.reminders.manage' => false,
                'business.integrations.view' => false,
                'business.integrations.manage' => false,
                'business.channels.view' => true,
                'business.channels.approve' => false,
                'business.voice_preferences.view' => true,
                'business.voice_preferences.manage' => false,
                'business.diagnostics.view' => true,
                'business.diagnostics.run' => false,
                'business.usage.view' => false,
                'business.billing.view' => false,
                'business.billing.portal' => false,
                'business.team.view' => false,
                'business.team.manage' => false,
                'business.roles.manage' => false,
                'business.security.view' => true,
                'business.security.manage' => false,
                'business.data_export.request' => false,
                'business.data_controls.view' => false,
                'business.data_delete.request' => false,
            ],
            'staff' => [
                'business.dashboard.view' => true,
                'business.conversations.view' => true,
                'business.conversations.manage' => false,
                'business.conversations.takeover' => false,
                'business.appointments.view' => true,
                'business.appointments.manage' => false,
                'business.providers.view' => true,
                'business.providers.manage' => false,
                'business.patients.view' => true,
                'business.patients.manage' => false,
                'business.services.view' => true,
                'business.services.manage' => false,
                'business.ai_content.view' => false,
                'business.ai_content.manage' => false,
                'business.reminders.view' => false,
                'business.reminders.manage' => false,
                'business.integrations.view' => false,
                'business.integrations.manage' => false,
                'business.channels.view' => true,
                'business.channels.approve' => false,
                'business.voice_preferences.view' => true,
                'business.voice_preferences.manage' => false,
                'business.diagnostics.view' => false,
                'business.diagnostics.run' => false,
                'business.usage.view' => false,
                'business.billing.view' => false,
                'business.billing.portal' => false,
                'business.team.view' => false,
                'business.team.manage' => false,
                'business.roles.manage' => false,
                'business.security.view' => true,
                'business.security.manage' => false,
                'business.data_export.request' => false,
                'business.data_controls.view' => false,
                'business.data_delete.request' => false,
            ],
        ],
    ];

    public function run(): void
    {
        foreach (self::TEMPLATE as $scope => $roles) {
            foreach ($roles as $role => $permissions) {
                foreach ($permissions as $permissionKey => $allowed) {
                    RolePermission::query()->updateOrCreate(
                        [
                            'scope' => $scope,
                            'role' => $role,
                            'permission_key' => $permissionKey,
                        ],
                        [
                            'allowed' => $allowed,
                        ],
                    );
                }
            }
        }
    }
}
