services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "9000"
    networks:
      - coolify

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    depends_on:
      - app
    environment:
      APP_UPSTREAM: app:9000
      PORT: 80             # CHANGED FROM 8080
    expose:
      - "80"               # CHANGED FROM "8080"
    networks:
      - coolify

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    command:
      - /usr/local/bin/start-queue
    networks:
      - coolify

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    command:
      - /usr/local/bin/start-scheduler
    networks:
      - coolify

# This tells your containers to bridge into Coolify's database network!
networks:
  coolify:
    external: true
